// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	aws "github.com/scys12/clean-architecture-golang/pkg/aws"
	mock "github.com/stretchr/testify/mock"
)

// S3Store is an autogenerated mock type for the S3Store type
type S3Store struct {
	mock.Mock
}

// UploadFileToS3 provides a mock function with given fields: _a0
func (_m *S3Store) UploadFileToS3(_a0 aws.FileParam) (string, error) {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(aws.FileParam) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(aws.FileParam) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
