// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/scys12/clean-architecture-golang/model"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetAllCategories provides a mock function with given fields: _a0
func (_m *Repository) GetAllCategories(_a0 context.Context) ([]*model.Category, error) {
	ret := _m.Called(_a0)

	var r0 []*model.Category
	if rf, ok := ret.Get(0).(func(context.Context) []*model.Category); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Category)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
